# Generated by Django 3.2.7 on 2022-02-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='attendees',
            field=models.ManyToManyField(related_name='gym_attendees', through='gym.Attendee', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym', verbose_name='Gym'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_gyms', to=settings.AUTH_USER_MODEL, verbose_name='Boss of the Gym'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gym.gym', verbose_name='Gym'),
        ),
    ]
