# Generated by Django 3.2.12 on 2022-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20220217_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Description'),
        ),
    ]
